from __future__ import annotations

from pathlib import Path


def test_env_example_contains_required_phase_1_variables() -> None:
    content = Path(".env.example").read_text(encoding="utf-8")
    keys = {
        line.split("=", 1)[0]: line.split("=", 1)[1]
        for line in content.splitlines()
        if line and not line.startswith("#") and "=" in line
    }

    required = {
        "BOT_NAME",
        "APP_ENV",
        "BOT_MODE",
        "LOG_LEVEL",
        "DATABASE_URL",
        "BYBIT_API_KEY",
        "BYBIT_API_SECRET",
        "BYBIT_ENV",
        "BYBIT_ENABLE_TRADING",
        "BYBIT_PUBLIC_BASE_URL",
        "BYBIT_PRIVATE_DEMO_BASE_URL",
        "BYBIT_PRIVATE_MAINNET_BASE_URL",
        "BYBIT_PRIVATE_RECV_WINDOW_MS",
        "BYBIT_PRIVATE_TIMEOUT_SECONDS",
        "BYBIT_ACCOUNT_REFRESH_INTERVAL_SECONDS",
        "TELEGRAM_BOT_TOKEN",
        "TELEGRAM_CHAT_ID",
        "LLM_API_KEY",
        "NEWS_CLASSIFIER_MODE",
        "LLM_PROVIDER_NAME",
        "LLM_API_URL",
        "LLM_MODEL",
        "LLM_CLASSIFIER_VERSION",
        "LLM_ALLOW_MOCK_FALLBACK",
        "LLM_CACHE_TTL_SECONDS",
        "LLM_TIMEOUT_SECONDS",
        "LLM_MAX_RETRIES",
        "LLM_BACKOFF_BASE_SECONDS",
        "LLM_RATE_LIMIT_PER_MINUTE",
        "LLM_MAX_CONCURRENT_REQUESTS",
        "LLM_CIRCUIT_BREAKER_FAILURE_THRESHOLD",
        "LLM_CIRCUIT_BREAKER_COOLDOWN_SECONDS",
        "LLM_MAX_INPUT_CHARACTERS",
        "LLM_MAX_OUTPUT_TOKENS",
        "LLM_HOURLY_REQUEST_BUDGET",
        "LLM_DAILY_REQUEST_BUDGET",
        "LLM_DAILY_TOKEN_BUDGET",
        "CODEX_CLI_ENABLED",
        "CODEX_CLI_PATH",
        "CODEX_CLI_MODEL",
        "CODEX_CLI_FALLBACK_MODEL",
        "CODEX_CLI_REASONING_EFFORT",
        "CODEX_CLI_FALLBACK_MIN_CONFIDENCE",
        "CODEX_CLI_MIN_NEWS_IMPORTANCE",
        "NEWS_POLL_INTERVAL_SECONDS",
        "NEWS_MAX_ITEM_AGE_MINUTES",
        "NEWS_MIN_IMPORTANCE_TO_CLASSIFY",
        "NEWS_ENABLE_RSS",
        "NEWS_RSS_URLS",
        "NEWS_ENABLE_MOCK_CLASSIFIER",
        "TEST_MODE",
        "AUTO_PAPER_EXECUTION",
        "SIGNAL_MIN_CLASSIFICATION_CONFIDENCE",
        "SIGNAL_MIN_NEWS_IMPORTANCE",
        "SIGNAL_TTL_SECONDS",
        "SIGNAL_CONFIRMATION_WINDOW_SECONDS",
        "SIGNAL_REEVALUATION_INTERVAL_SECONDS",
        "SIGNAL_CONFLICT_THRESHOLD_PCT",
        "SIGNAL_MIN_EXPECTED_EDGE_BPS",
        "SIGNAL_DEFAULT_STOP_LOSS_PCT",
        "SIGNAL_DEFAULT_TAKE_PROFIT_PCT",
        "ALLOWED_SYMBOLS",
        "MARKET_DATA_PROVIDER",
        "MARKET_DATA_TIMEOUT_SECONDS",
        "MARKET_DATA_HISTORY_LIMIT",
        "TRADING_PAUSED",
        "PAPER_STARTING_EQUITY_USDT",
        "PAPER_DAILY_PNL_PCT",
        "PAPER_WEEKLY_PNL_PCT",
        "PAPER_CONSECUTIVE_LOSSES",
        "PAPER_TAKE_PROFIT_PCT",
        "PAPER_POSITION_TIMEOUT_MINUTES",
        "PAPER_MAX_TOTAL_OPEN_POSITIONS",
        "PAPER_SYMBOL_COOLDOWN_SECONDS",
        "PAPER_GLOBAL_ENTRY_COOLDOWN_SECONDS",
        "PAPER_MAX_DAILY_NET_LOSS_PCT",
        "PAPER_MAX_WEEKLY_NET_LOSS_PCT",
        "PAPER_MAX_ACCOUNT_DRAWDOWN_PCT",
        "DEFAULT_PAPER_FEES_BPS",
        "DEFAULT_SLIPPAGE_BPS",
        "PAPER_MAKER_FEE_BPS",
        "PAPER_TAKER_FEE_BPS",
        "PAPER_SLIPPAGE_BPS",
        "MIN_NET_EDGE_BPS",
        "MAX_POSITION_NOTIONAL_USDT",
        "MAX_POSITION_NOTIONAL_PCT_OF_EQUITY",
        "MIN_POSITION_NOTIONAL_USDT",
        "MAX_RISK_PER_TRADE_PCT",
        "MAX_DAILY_LOSS_PCT",
        "MAX_WEEKLY_LOSS_PCT",
        "MAX_LEVERAGE",
        "MAX_SPREAD_BPS",
        "MIN_LLM_CONFIDENCE",
        "MIN_EXPECTED_EDGE_BPS",
    }

    assert required <= set(keys)
    assert keys["BOT_MODE"] != "LIVE"
    assert keys["DATABASE_URL"].startswith("postgresql+psycopg://")
    assert all(keys[key] for key in required)
